<a href="https://colab.research.google.com/github/RohanKJoseph/IPRS_Tasks/blob/main/Task_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Transforming Categorical Data into Numerical Format

In [ ]:
#importing therequired libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
#creating the dummy data set and dataframe

data = {
    'PAtient_ID': ["P1", "P2", "P3", "P4", "P5"],
    'Gender': ["M","F","F","M","F"],
    "AppointmentType" : ["Routine","Emergency","Routine","Follow-up","Emergency"],
    "City":["New York","Los Angeles","Chicago","New York","Chicago"]
}

df = pd.DataFrame(data)
print("Original Data set : \n",df)

Original Data set :
   PAtient_ID Gender AppointmentType         City
0         P1      M         Routine     New York
1         P2      F       Emergency  Los Angeles
2         P3      F         Routine      Chicago
3         P4      M       Follow-up     New York
4         P5      F       Emergency      Chicago

##Inspect the Dataset

In [ ]:
df.info()
print("\n")
df.describe() #to check for the numeric statistics

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PAtient_ID       5 non-null      object
 1   Gender           5 non-null      object
 2   AppointmentType  5 non-null      object
 3   City             5 non-null      object
dtypes: object(4)
memory usage: 292.0+ bytes

       PAtient_ID Gender AppointmentType      City
count           5      5               5         5
unique          5      2               3         3
top            P1      F         Routine  New York
freq            1      3               2         2

In [ ]:
#checking for missing values
df.isnull().sum()

#from its output its clear that there is no missing vlues

PAtient_ID         0
Gender             0
AppointmentType    0
City               0
dtype: int64

In [ ]:
# creating the copy of the data for applying both of the operation

df_label = df.copy()
df_onehot = df.copy()

##Label Encoding

In [ ]:
#Using LabelEncoder we encode each categorical column

#initialising the labelencoder

le = LabelEncoder()

#applying the label encoder on the catogarical columns

catogarical_columns = df_label.select_dtypes(include=['object']).columns #finding the catogarical clms to encode
#applying on each
df_label[catogarical_columns] = df_label[catogarical_columns].apply(le.fit_transform)

print("Label Encoded Data : \n",df_label) #displaying the output

Label Encoded Data :
    PAtient_ID  Gender  AppointmentType  City
0           0       1                2     2
1           1       0                0     1
2           2       0                2     0
3           3       1                1     2
4           4       0                0     0

##One-Hot Encoding

In [ ]:
#Using one hot encoding we encode each categorical column

categorical_cols = ['Gender', 'AppointmentType', 'City']

#applying the one hot encoder on the catogarical columns using the dummies
df_onehot = pd.get_dummies(df, columns=categorical_cols , dtype=int)

print("--- One-Hot Encoded Dataset ---")
print(df_onehot)   #displying the output

--- One-Hot Encoded Dataset ---
  PAtient_ID  Gender_F  Gender_M  AppointmentType_Emergency  \
0         P1         0         1                          0
1         P2         1         0                          1
2         P3         1         0                          0
3         P4         0         1                          0
4         P5         1         0                          1

   AppointmentType_Follow-up  AppointmentType_Routine  City_Chicago  \
0                          0                        1             0
1                          0                        0             0
2                          0                        1             1
3                          1                        0             0
4                          0                        0             1

   City_Los Angeles  City_New York
0                 0              1
1                 1              0
2                 0              0
3                 0              1
4                 0              0